---
date: "2018-11-28T15:14:39+10:00"
title: Full CV
Weight: 12
---

# EDUCATION
The University of Texas at Dallas, Richardson, TX  
Ph.D., Cognition and Neuroscience, Aug. 2016 - present  
M.S., Applied Cognition and Neuroscience, Aug. 2014- May 2016

Baylor University, Waco, TX  
B.S., Neuroscience, Honors Program Graduate, Aug. 2014  
Minor: Journalism: News-Editorial

# RESEARCH EXPERIENCE
## School of Brain and Behavioral Sciences, the University of Texas at Dallas, Richardson, TX  
Graduate Research Assistant (Aug. 2014– present), Army Research Lab Graduate Research Assistant (Jan. 2019 – present)  

**Research Advisor: Dr. Dan Krawczyk (Aug. 2016 – present)**  

*	tDCS and Deception project (Jan 2019 – present)
    +	Design and implement an experience that will examine the effect of tDCS on implicit and explicit deception detections. Utilize self-report acculturation measures to understand the link between culture and tDCS stimulation and the link between culture and implicit/explicit deception detection
    +	Manage a team of 8-10 undergraduate and master’s research interns
    +	Lead weekly journal club sessions to explore literature behind tDCS, deception, and social cognition in depth
*	Cyber Deception (Jan 2018 – present)
    *	Work across disciplines with computer science professors and graduate students to explore novel ways to understand cyber deception and how machines and humans can interact collaboratively to make decisions
    *	Assist in development of neural networks that may be able to detect deception
    *	Study human behavior in detect deception and how quickly judgements are made
*	BIOmarkers of dynamic Sociocultural capacities: Integrating Neurotechnologies and Novel Math (BIOSINM) project (Jan. 2015-present)
    *	Development of the Sociocultural Stimuli Database of truth-telling and lie-telling cross cultural stimuli
    *	Neuroimaging experimental design and data collection
    *	Analysis of behavioral and neuroimaging IAT data using univariate and multivariate approaches
    *	Currently assisting with preparation of manuscripts related to this project
    
**Research Advisor: Dr. Alice O’Toole (Aug. 2014 – Aug. 2016)**

*	BIOSINM project
*	Data collection for body image study

## Department of Psychology and Neuroscience, Baylor University, Waco, TX  
Undergraduate Research Assistant, Honors Thesis Student (Aug. 2011 – Aug. 2014)  
**Research Advisor: Dr. Wade Rowatt**  

*	Carried out a project that examined the effect of religious priming on implicit and explicit attitudes towards interracial couples using the web Implicit Association Test and Amazon Mechanical Turk
*	Successfully defended an honors thesis project that examined implicit and explicit attitudes towards interracial couples
    +	Developed the survey and IAT, analyzed data
*	Facilitated a social and affective neuroscience reading group 
*	Trained other undergraduate research assistants on Qualtrics and Mechanical Turk
*	Presented research at regional and national conferences

## Summer Undergraduate Research Program, the University of Texas Medical Branch, Galveston, TX
Summer Undergraduate Research Student (June 2012-Aug. 2012)  
**Research Advisors: Drs. Christine Arcari and Kirk Smith**   

*	Designed and implemented a project that examined inter-professional perceptions between health profession students

## Department of Speech and Hearing Sciences, University of North Texas, Denton, TX
Texas Academy of Math and Science Student (Jan. 2010 – May 2011)
**Research Advisor: Dr. Fang Ling-Lu** 

*	Analyzed videos of vocal folds to assess and understand current rating scales for patient vocal folds

# PUBLICATIONS
Young, L., Nguyen, L., Hahn, C. A., O’Toole, A., Bartlett, J., Krawczyk, D. C. (in prep). Cross-Cultural Trust and Deception. 

Nguyen, L., Young, L., Krawczyk, D. (in prep). Analysis of implicit and explicit lie detection using fMRI. 

Nguyen, L., Young, L., Krawczyk, D. (in prep). Cross-Cultural Trustworthiness Trait Evaluations Based Upon Dynamic Presentations

# ACADEMIC CONFERENCES AND PRESENTATIONS
## Oral Presentations  
Nguyen, L. (2019, March). Using the Implicit Association Test to Detect Cross-Cultural Deception. Brown Bag Presentation at the Developmental, Cognitive, and Social Psychology Series, Richardson, Texas

Nguyen, L., Rowatt, W. (2014, April). Personality Correlates of Implicit and Explicit Attitudes Towards Interracial Attraction. Platform Presentation for Psychology and Neuroscience at the Baylor University Undergraduate Research and Scholarly Activities Scholar’s Week, Waco, Texas.

## Poster Presentations
Nguyen, L., Young, L., Krawczyk, D. (2019, February). Neural Implicit Mechanisms of Deception Detection. Poster session presented at the Society for Personality and Social Psychology Annual Meeting, Portland, Oregon.

Nguyen, L., Young, L., Rakic, J., Krawczyk, D. (2017, March). Neural Implicit Mechanisms of Deception Detection. Poster session presented at the Social and Affective Neuroscience Society 10th Annual Meeting, Los Angeles, California.

Nguyen, L., Rowatt, W. (2014, February). Personality Correlates of Implicit and Explicit Attitudes Towards Interracial Attraction. Poster session presented at the Society of Personality and Social Psychology 15th Annual Meeting, Austin, Texas.

Nguyen, L., Rowatt, W. (2013, April). Implicit and Explicit Correlates of Interracial Attraction. Poster session presented at Southwest Psychology Association 2013, Fort Worth, Texas.

Nguyen, L., Rowatt, W. (2013, April). Implicit and Explicit Correlates of Interracial Attraction. Poster session presented at the Baylor University Undergraduate Research and Scholarly Activities Scholar’s Week, Waco, Texas.

Nguyen, L., Arcari, C., Smith, K., (2012, August). Building interprofessional teams: how community service learning can change disciplinary perceptions. Poster session presented at SURP Summer Poster Presentation, Galveston, Texas.

# PUBLIC PRESENTATIONS
## Talks
Nguyen, L. (March 2019). How do we detect lies? Science in the City. Dallas, Texas.

Nguyen, L. (July 2019). Understanding Implicit Deception Detection. Sips and Sciences. Dallas, Texas

## Print
Kuchment, A. (March 2019). Explore the hidden wonders, technology happening right here in Dallas with Science in the City. The Dallas Morning News.

## Radio
Fiaschetti, B. (Host). (June 2019). OneLife Radio[Audio podcast]

# PROFESSIONAL EXPERIENCE
## American Airlines (June 2019 – Sept. 2019)
User Research Intern

*	Conduct usability research on digital channels for a major airline
*	Assist in user testing using a variety of platforms including in-person (airport testing and observation) and online (UserTesting and Qualtrics)
*	Create an online center of excellence for the user experience team on Microsoft SharePoint by compiling and writing documentation on a variety of research methodologies
*	Assist of developing a test and analysis plan to evaluate and understand the social implications of a new enterprise social software

## Various Yoga Studios (Oct. 2017-Present)
Yoga Instructor

*	Teach 4-6 weekly yoga classes for a variety of adult populations
*	Create sequences and playlists for powerful yoga classes ranging from vinyasa to yoga sculpt to restorative yoga
*	Represent studios in outside events around the DFW metroplex

# TEACHING EXPERIENCE
## The University of Texas at Dallas
Teaching Assistant

*	Experimental Projects (Fall 2017)
*	Cognitive Psychology (Spring 2018)
*	Neuroanatomy (Fall 2018)

# HONORS AND AWARDS

*	Distinguished Student in Neuroscience Research (April 2013)
*	SURP Most Outstanding Poster in Population Health Sciences (Aug. 2012)

# TECHNICAL SKILLS	

* User Research Tools: Amazon Mechanical Turk, Qualtrics Survey Software, Inquisit, EPrime, UserTesting
*	Data Analysis: SPSS, MatLab, R, Python
*	Other: Mac OS, Windows OS, Adobe Creative Suite, Digital Photography, Videography, Microsoft Suite, Microsoft SharePoint

# UNIVERSITY SERVICE

Student Media Operating Board (Fall 2017, Fall 2018, Spring 2019, Fall 2019)
UTD TV: Station Manager (May 2015 - May 2016), News Director (Jan. 2015 - May 2015) 
The Mercury: Senior Staff Writer and Blogger (Aug. 2014 - May 2016) 
The Baylor Lariat: Copy Desk Chief (Aug. 2013 - May 2014), Arts and Entertainment Editor (Jan. 2013 - May 2013), Staff Writer (Aug. 2012 – Dec. 2012)

# PROFESSIONAL AFFILIATIONS

Social and Affective Neuroscience Society
Society of Personality and Social Psychology
Southwest Psychological Association
Association of Health Care Journalists
National Association of Science Writers
