---
date: "2018-11-28T15:14:39+10:00"
title: Presentations
Weight: 5
---

# ACADEMIC CONFERENCES AND PRESENTATIONS
## Oral Presentations  
Nguyen, L. (2019, March). Using the Implicit Association Test to Detect Cross-Cultural Deception. Brown Bag Presentation at the Developmental, Cognitive, and Social Psychology Series, Richardson, Texas

Nguyen, L., Rowatt, W. (2014, April). Personality Correlates of Implicit and Explicit Attitudes Towards Interracial Attraction. Platform Presentation for Psychology and Neuroscience at the Baylor University Undergraduate Research and Scholarly Activities Scholar’s Week, Waco, Texas.

## Poster Presentations
Nguyen, L., Young, L., Krawczyk, D. (2019, February). Neural Implicit Mechanisms of Deception Detection. Poster session presented at the Society for Personality and Social Psychology Annual Meeting, Portland, Oregon.

Nguyen, L., Young, L., Rakic, J., Krawczyk, D. (2017, March). Neural Implicit Mechanisms of Deception Detection. Poster session presented at the Social and Affective Neuroscience Society 10th Annual Meeting, Los Angeles, California.

Nguyen, L., Rowatt, W. (2014, February). Personality Correlates of Implicit and Explicit Attitudes Towards Interracial Attraction. Poster session presented at the Society of Personality and Social Psychology 15th Annual Meeting, Austin, Texas.

Nguyen, L., Rowatt, W. (2013, April). Implicit and Explicit Correlates of Interracial Attraction. Poster session presented at Southwest Psychology Association 2013, Fort Worth, Texas.

Nguyen, L., Rowatt, W. (2013, April). Implicit and Explicit Correlates of Interracial Attraction. Poster session presented at the Baylor University Undergraduate Research and Scholarly Activities Scholar’s Week, Waco, Texas.

Nguyen, L., Arcari, C., Smith, K., (2012, August). Building interprofessional teams: how community service learning can change disciplinary perceptions. Poster session presented at SURP Summer Poster Presentation, Galveston, Texas.

# PUBLIC PRESENTATIONS
## Talks
Nguyen, L. (March 2019). How do we detect lies? Science in the City. Dallas, Texas.

Nguyen, L. (July 2019). Understanding Implicit Deception Detection. Sips and Sciences. Dallas, Texas

## Print
Kuchment, A. (March 2019). Explore the hidden wonders, technology happening right here in Dallas with Science in the City. The Dallas Morning News.

## Radio
Fiaschetti, B. (Host). (June 2019). OneLife Radio[Audio podcast]

